---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin
spec:
  selector:
    app: jellyfin
  type: ClusterIP
  ports:
    - name: jellyfin
      protocol: TCP
      port: 8096
      targetPort: jellyfin
